//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koob.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class koobEntities : DbContext
    {
        public koobEntities()
            : base("name=koobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<calificaciones> calificaciones { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<deseos> deseos { get; set; }
        public virtual DbSet<fotos> fotos { get; set; }
        public virtual DbSet<interesados> interesados { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<reportes> reportes { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
