//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koob.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public int cal_codigo { get; set; }
        public int cal_valor { get; set; }
        public string usu_email { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
