//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koob.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos
    {
        public int fot_codigo { get; set; }
        public byte[] fot_foto1 { get; set; }
        public byte[] fot_foto2 { get; set; }
        public byte[] fot_foto3 { get; set; }
        public byte[] fot_foto4 { get; set; }
        public byte[] fot_foto5 { get; set; }
        public int lib_codigo { get; set; }
        public int usu_codigo { get; set; }
    
        public virtual libros libros { get; set; }
    }
}
