//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koob.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public libros()
        {
            this.fotos = new HashSet<fotos>();
            this.interesados = new HashSet<interesados>();
        }
    
        public int lib_codigo { get; set; }
        public string lib_isbn { get; set; }
        public string lib_descripcion { get; set; }
        public string lib_ubicacion { get; set; }
        public string usu_email { get; set; }
        public int cat_codigo { get; set; }
        public string lib_autores { get; set; }
        public string lib_imagen { get; set; }
        public string lib_sinopsis { get; set; }
    
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fotos> fotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interesados> interesados { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
